hmcts/finrem-notification-service

Jenkinsfile_CNP
build.gradle
infrastructure/main.tf
infrastructure/variables.tf
src/test/java/uk/gov/hmcts/reform/finrem/notifications/NotificationApplicationTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/category/SmokeTest.java

[PREVIEW] - Fr 414_CNP_pipeline_setup

---

.travis.yml
infrastructure/output.tf

- removed before_install from Travis.yml
- removed output variables from CNP related file

Fr 414 code quality checks

---

.travis.yml
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/variables.tf

- Updated CNP pipeline settings

[PREVIEW] - Fr 414 CNP Pipeline

---

infrastructure/main.tf

FR_414_CNP

---

README.md
docker-compose.yml
infrastructure/main.tf
infrastructure/output.tf
src/main/resources/application.properties

Added readme
Dockerised
added output variables

Fr 414 cnp

---

build.gradle
dependency-check-suppressions.xml
docker-compose.yml
src/main/java/uk/gov/hmcts/reform/finrem/notifications/config/SwaggerConfiguration.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/finrem/notifications/client/EmailClientTest.java
src/test/resources/application.properties

- sonar exclusions
- swagger enabled
- unit test properties updated.
- docker compose updated.

FR_483_swagger_doc

---

build.gradle
dependency-check-suppressions.xml
docker-compose.yml
src/main/java/uk/gov/hmcts/reform/finrem/notifications/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationController.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/finrem/notifications/client/EmailClientTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationControllerTest.java
src/test/resources/application.properties

Fr 483 swagger doc

---

src/test/java/uk/gov/hmcts/reform/finrem/notifications/functionalTest/NotifyHwfSuccessfulTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/functionaltest/NotifyHwfSuccessfulTest.java

Fr 497 functional test

---

src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationController.java
src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationControllerTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/functionaltest/NotifyConsentOrderAvailableTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/functionaltest/NotifyConsentOrderNotApprovedTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailServiceTest.java
src/test/resources/application.properties
src/test/resources/fixtures/consentOrderAvailable.json
src/test/resources/fixtures/consentOrderNotApproved.json

- implemented rest endpoints
- tests

FR_401_notification && FR_403_consent_order_notification

---

src/main/resources/application.properties

- Added smart survey link for FR

FR_434_FR_smart_link_survey

---

build.gradle
src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyAssignToJudgeTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyConsentOrderAvailableTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyConsentOrderMadeTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyConsentOrderNotApprovedTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyHwfSuccessfulTest.java

- renamed folder name and configure build.gradle
- removed sonar exclusions

FR_722_integration_tests

---

Dockerfile

- fixed build issue with docker image

FR_716_Smoke_tests

---

build.gradle
charts/finrem-ns/Chart.yaml
charts/finrem-ns/requirements.yaml
charts/finrem-ns/values.aat.template.yaml
charts/finrem-ns/values.preview.template.yaml
charts/finrem-ns/values.yaml
dependency-check-suppressions.xml
src/main/resources/bootstrap.yaml

Implement Helm Charts.

---

build.gradle
src/main/java/uk/gov/hmcts/reform/finrem/notifications/NotificationApplication.java

- cleanup dependencies
https://tools.hmcts.net/jira/browse/FR-819
- cleanup dependencies
```
[ ] Yes
[X ] No
```

FR-819_health_check_cache_and_cleanup

---

src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/NotificationRequest.java
src/main/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailService.java
src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/NotificationRequestTest.java
src/test/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailServiceTest.java
src/test/resources/application.properties

- implementation for contested email
- unit tests
https://tools.hmcts.net/jira/browse/FR-1137
contested_court_details_in_email for HWF successful
```
[ ] Yes
[ X] No
```

FR_1137_ contested_court_details_in_email

---

Jenkinsfile_CNP
charts/finrem-ns/Chart.yaml
charts/finrem-ns/values.aat.template.yaml
charts/finrem-ns/values.preview.template.yaml
charts/finrem-ns/values.yaml

Charts and Jenkinsfile changed for AKS migration

---

infrastructure/main.tf

Fixing module source

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/FR-1378
Removing pipeline stop.
```
[ ] Yes
[x] No
```

Removing pipeline fuse to deploy

---

build.gradle
dependency-check-suppressions.xml

Ignoring dependency vulnerability we can not fix atm

---

Jenkinsfile_CNP

Restoring pipeline fuse to stop deploying to prod

---

charts/finrem-ns/Chart.yaml
charts/finrem-ns/values.yaml

https://tools.hmcts.net/jira/browse/FR-1378
```
[ ] Yes
[x] No
```

FR-1378: bumping chart version

---

charts/finrem-ns/values.aat.template.yaml
charts/finrem-ns/values.preview.template.yaml
charts/finrem-ns/values.yaml

Removing swagger in prod and enabling in AAT

---

charts/finrem-ns/values.aat.template.yaml
charts/finrem-ns/values.preview.template.yaml
charts/finrem-ns/values.yaml
dependency-check-suppressions.xml

Swagger flag

---

charts/finrem-ns/values.aat.template.yaml
charts/finrem-ns/values.preview.template.yaml
charts/finrem-ns/values.yaml
dependency-check-suppressions.xml

removing Swagger flag

---

infrastructure/main.tf

Fix terraform script

---

infrastructure/main.tf

Making string a boolean

---

infrastructure/main.tf

Terraform syntax fix

---

infrastructure/main.tf

terraform fix

---

build.gradle

Adding reforms logging dependencies

---

build.gradle
infrastructure/main.tf
infrastructure/variables.tf

Hotfix infra

---

src/main/resources/application.properties
src/test/resources/application.properties

https://tools.hmcts.net/jira/browse/RPET-195
Update old court email to new. 
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```

RPET-195: update court email

---

build.gradle

Bumping tomcat to fix CVE-2020-9484
```
[ ] Yes
[x] No
```

Bumping tomcat to version 9.0.35

---

audit.json
build.gradle
src/main/resources/application.properties

fix owasp dependency check error

suppress zap dependency check error

---

src/main/resources/application.properties
src/test/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailServiceTest.java
src/test/resources/application.properties

https://tools.hmcts.net/jira/browse/RPET-164
Added the newly created FRCs to the mapping configuration...
```
[ ] Yes
[X] No
```

RPET-164 Add the new FRCs for a complete mapping

---

security.sh

security scan update for nightly

---

src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ConsentedNotificationController.java
src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationController.java

Update contested/consented notification controller logs

---

README.md
charts/finrem-ns/Chart.yaml
charts/finrem-ns/requirements.yaml

https://tools.hmcts.net/jira/browse/FR-1981
Upgrade for Helm Chart descriptor to API version 2
```
[ ] Yes
[x] No
```

Upgrade Helm chart to v2

---

README.md
build.gradle
charts/finrem-ns/Chart.yaml
charts/finrem-ns/values.yaml
src/main/resources/application.properties

https://tools.hmcts.net/jira/browse/FR-1984
Updates base chart to latest version
```
[ ] Yes
[x] No
```

Update base chart to latest version

---

src/main/resources/bootstrap.yaml

None
Loads AI key from key vault
```
[ ] Yes
[x] No
```

Load AI key from vault

---

audit.json

No code changes- just ignore false positives.

suppress zap nightly build failure errors

---

charts/finrem-ns/Chart.yaml
charts/finrem-ns/values.yaml
src/main/resources/bootstrap.yaml

None
Includes AI secret in Helm chart
```
[ ] Yes
[x] No
```

Include AI secret in Helm chart

---

README.md
build.gradle

https://tools.hmcts.net/jira/browse/DFR-76

DFR-76 SpringBoot Update

---

audit.json

- [ X] commit messages are meaningful and follow good commit message guidelines
- [X ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/DFR-114
```
[ ] Yes
[X ] No
```

DFR-114  Zaproxy Error Suppression.

---

build.gradle

https://tools.hmcts.net/jira/browse/DFR-564
```
[ ] Yes
[ x] No
```

DFR-564-FixGlassFishVulne

---

build.gradle
charts/finrem-ns/Chart.yaml

1. Fix vulnerabilities 
2. Remove deprecated jcenter
3. Bump Chart version

fix vulnerabilities and remove deprecated jcenter

---

charts/finrem-ns/Chart.yaml

bump java and chart version

---

build.gradle
charts/finrem-ns/Chart.yaml

- bump java chart version
- fix jackson vulnerability

fix vulnerabilities and bump chart version

---

build.gradle

DFR-975
resolve spring dependency
```
[ ] Yes
[ x] No
```

DFR-975: resolve spring dependency

---

.github/renovate.json
charts/finrem-ns/Chart.yaml

[DFR-1162](https://tools.hmcts.net/jira/browse/DFR-1162)
Enable renovate
```
[ ] Yes
[ ] No
```

DFR-1162: Enable renovate

---

build.gradle
dependency-check-suppressions.xml

[DFR-1172](https://tools.hmcts.net/jira/browse/DFR-1172)
Suppress log4j vulnerability
```
[ ] Yes
[x ] No
```

DFR-1172: Suppress log4j vulnerability

---

dependency-check-suppressions.xml

Suppressing Jakarta and Spring Framework

---

build.gradle

dependencies

---

build.gradle

updrade 1.33 version

---

README.md

inserted blank line on README.md

---

build.gradle
dependency-check-suppressions.xml

Fix dependency-check-suppressions

---

dependency-check-suppressions.xml

Suppress apache commons

---

dependency-check-suppressions.xml

Suppressing bad CVE

---

dependency-check-suppressions.xml

Suppressing snakeyaml

---

dependency-check-suppressions.xml

Suppressing Apache commons

---

charts/finrem-ns/Chart.yaml

DFR-1758
update-chart-version
```
[ ] Yes
[x] No
```

DFR-1758: update-chart-version

---

dependency-check-suppressions.xml
src/main/resources/application.properties
src/test/resources/application.properties

DFR-1638: High Court

---

charts/finrem-ns/Chart.yaml

[DFR-1783](https://tools.hmcts.net/jira/browse/DFR-1783)
Upgrade charts
```
[ ] Yes
[x ] No
```

DFR-1783: Upgrade charts

---

build.gradle
dependency-check-suppressions.xml

fix owasp dependency

---

dependency-check-suppressions.xml

dependency fix patch

---

build.gradle
dependency-check-suppressions.xml

Fixed nightly-vulnerabilities

---

dependency-check-suppressions.xml

supress tomcat cve

---

README.md
dependency-check-suppressions.xml

Test PR for internal URL
